[package]
name = "graphviz"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Robotechnic"]
license = "MIT"
repository = "https://github.com/Robotechnic/graphviz.git"
description = "Graphviz bindings for typst"
compiler = "0.8.0"
exclude = ["graphviz_interface/*", "examples/*", ".gitignore", "Makefile"]
keywords = ["graphviz","graph"]